#pragma once

#define VICONDATASTREAMSDK_C_VERSION_REVISION_CONTROL_SYSTEM "unknown"
#define VICONDATASTREAMSDK_C_VERSION_REVISION 0
#define VICONDATASTREAMSDK_C_VERSION_MONOTONIC_REVISION 0
#define VICONDATASTREAMSDK_C_VERSION_PUBLIC_REVISION_STRING "0"
#define VICONDATASTREAMSDK_C_VERSION_BRANCH "unknown"
#define VICONDATASTREAMSDK_C_VERSION_REPOSITORY "unknown"
#define VICONDATASTREAMSDK_C_VERSION_CHANGESET "0"
#define VICONDATASTREAMSDK_C_VERSION_LOCAL_CHANGESET "0"
#define VICONDATASTREAMSDK_C_VERSION_LOCAL_BRANCH "unknown"

#define VICONDATASTREAMSDK_C_VERSION_MAJOR 1
#define VICONDATASTREAMSDK_C_VERSION_MINOR 11
#define VICONDATASTREAMSDK_C_VERSION_POINT 0
#define VICONDATASTREAMSDK_C_VERSION_RELEASE ""
#define VICONDATASTREAMSDK_C_VERSION_SUPPLEMENTAL ""

#define VICONDATASTREAMSDK_C_FULL_VERSION_STRING "1.11.0.0"
#define VICONDATASTREAMSDK_C_VERSION_STRING "1.11"
#define VICONDATASTREAMSDK_C_COMPANY "Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_C_COPYRIGHT "Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_C_TRADEMARK "Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_C_PROJECT_NAME "ViconDataStreamSDK_C"

#define VICONDATASTREAMSDK_C_FULL_VERSION_STRING_L L"1.11.0.0"
#define VICONDATASTREAMSDK_C_VERSION_STRING_L L"1.11"
#define VICONDATASTREAMSDK_C_COMPANY_L L"Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDK_C_COPYRIGHT_L L"Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDK_C_TRADEMARK_L L"Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDK_C_PROJECT_NAME_L L"ViconDataStreamSDK_C"
