#pragma once

#define VICONDATASTREAMSDKCORE_VERSION_REVISION_CONTROL_SYSTEM "unknown"
#define VICONDATASTREAMSDKCORE_VERSION_REVISION 0
#define VICONDATASTREAMSDKCORE_VERSION_MONOTONIC_REVISION 0
#define VICONDATASTREAMSDKCORE_VERSION_PUBLIC_REVISION_STRING "0"
#define VICONDATASTREAMSDKCORE_VERSION_BRANCH "unknown"
#define VICONDATASTREAMSDKCORE_VERSION_REPOSITORY "unknown"
#define VICONDATASTREAMSDKCORE_VERSION_CHANGESET "0"
#define VICONDATASTREAMSDKCORE_VERSION_LOCAL_CHANGESET "0"
#define VICONDATASTREAMSDKCORE_VERSION_LOCAL_BRANCH "unknown"

#define VICONDATASTREAMSDKCORE_VERSION_MAJOR 1
#define VICONDATASTREAMSDKCORE_VERSION_MINOR 11
#define VICONDATASTREAMSDKCORE_VERSION_POINT 0
#define VICONDATASTREAMSDKCORE_VERSION_RELEASE ""
#define VICONDATASTREAMSDKCORE_VERSION_SUPPLEMENTAL ""

#define VICONDATASTREAMSDKCORE_FULL_VERSION_STRING "1.11.0.0"
#define VICONDATASTREAMSDKCORE_VERSION_STRING "1.11"
#define VICONDATASTREAMSDKCORE_COMPANY "Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDKCORE_COPYRIGHT "Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDKCORE_TRADEMARK "Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDKCORE_PROJECT_NAME "ViconDataStreamSDKCore"

#define VICONDATASTREAMSDKCORE_FULL_VERSION_STRING_L L"1.11.0.0"
#define VICONDATASTREAMSDKCORE_VERSION_STRING_L L"1.11"
#define VICONDATASTREAMSDKCORE_COMPANY_L L"Vicon Motion Systems Ltd"
#define VICONDATASTREAMSDKCORE_COPYRIGHT_L L"Copyright \x00A9 2020 Vicon Motion Systems Ltd. All rights reserved."
#define VICONDATASTREAMSDKCORE_TRADEMARK_L L"Vicon\x00AE is a registered trademark of OMG Plc."
#define VICONDATASTREAMSDKCORE_PROJECT_NAME_L L"ViconDataStreamSDKCore"
